title: Dromologue
author: Justin
url: https://dromologue.com
description: Velocity and Value. That is all.

permalink: /:slug

favicon: "/favicon.ico"

theme_config:
  appearance: "dark"
  appearance_toggle: false
  show_description: true
  show_navbar: false
  show_footer: true
  show_copyright: true
  show_projects: false
  show_blog: false
  show_old_projects: false
  show_misc_list: false

highlighter: rouge

sass:
  style: compressed
