title: Dromologue
author: Justin
url: https://dromologue.com
description: >
  Velocity and Value. That is all.

permalink: /:slug

favicon: "./favicon.ico"

remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark"
  appearance_toggle: false
  back_home_text: "home"
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: false
  show_footer: true
  show_copyright: true
  show_projects: false
  show_blog: false
  show_old_projects: false
  show_misc_list: false
  show_reading_time: false
  show_tags: false

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
